// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxq4MFB5shf6GXPeYe4ZwRb_HpV7U4HS4',
    appId: '1:113254122529:web:019343d1d089f29a2d8f60',
    messagingSenderId: '113254122529',
    projectId: 'doctorappoinment4b',
    authDomain: 'doctorappoinment4b.firebaseapp.com',
    storageBucket: 'doctorappoinment4b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqZO3ZD3YRnqfLLPRco0UDkugu040q0W8',
    appId: '1:113254122529:android:ffbb7a7482c913092d8f60',
    messagingSenderId: '113254122529',
    projectId: 'doctorappoinment4b',
    storageBucket: 'doctorappoinment4b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8tCkUKPRTn5BfN6WYrnnITbvcQew8jE0',
    appId: '1:113254122529:ios:9e264bdad595b5672d8f60',
    messagingSenderId: '113254122529',
    projectId: 'doctorappoinment4b',
    storageBucket: 'doctorappoinment4b.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8tCkUKPRTn5BfN6WYrnnITbvcQew8jE0',
    appId: '1:113254122529:ios:9e264bdad595b5672d8f60',
    messagingSenderId: '113254122529',
    projectId: 'doctorappoinment4b',
    storageBucket: 'doctorappoinment4b.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCxq4MFB5shf6GXPeYe4ZwRb_HpV7U4HS4',
    appId: '1:113254122529:web:56b64738023c95e42d8f60',
    messagingSenderId: '113254122529',
    projectId: 'doctorappoinment4b',
    authDomain: 'doctorappoinment4b.firebaseapp.com',
    storageBucket: 'doctorappoinment4b.firebasestorage.app',
  );

}